### ISSUE TITLE
Design System Checklist

### ISSUE THREAD

**Issue by DuetoPark** [DuetoPark/neneb-neneneb#2]
## 1. Variable_(2021.11.06)
- [ ] Color
- [ ] Typography
- [ ] Grid
- [ ] Responsive

**Comment by DuetoPark** [comment]
## 2. Mixin_(2021.11.06)
- [ ] Text Style
- [ ] Position
- [ ] Flexbox
- [ ] Scrollbar
- [ ] Star-rating

**Comment by DuetoPark** [comment]
## 3. Module_(2021.11.06)
### Layout 뿌시기
- [ ] 글자수가 많을 때
- [ ] Image가 정사각형이 아닐 때

### Avatar
- [ ] 사용자의 프로필 이미지가 있을 때
- [ ] 사용자의 프로필 이미지가 없을 때
- [ ] Image가 정사각형이 아닐 때

### 구현 순서
| Type                        | Default | 상태 디자인 | Desc.                           |
|----------------------|----------|--------------|-------------------------|
| Price                       |  X          | X                  | 글꼴 Tahoma               |
| Star                         |              | X                  | .is-active 스타일 구현 |
| Button                    |              |                     |  |
| Pagination              |              |                     | .is-active 스타일 구현 |
| Dropdown              |              |                     |  |
| From-Base              |              |                     |  |
| From-Select            |              |                     |  |
| From-Search Input |              |                     |  |
